version: '3.8'

services:
  pg:
    image: bitnami/postgresql:13.16.0
    container_name: WebScrapping-food
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docWeb
      - POSTGRES_PASSWORD=docWeb@123
      - POSTGRES_DB=webfood
    volumes:
      - pgdata:/bitnami/postgresql
    restart: unless-stopped

volumes:
  pgdata:
